spring:
  application:
    name: eureka-server
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  cloud:
    config:
      enabled: false

server:
  port: 10002

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: ${eureka.instance.hostname}:${server.port}/eureka/
#
#replica:
#  key: ${random.uuid}